MachineKey: "${ZITADEL_MACHINEKEY}"
Database:
  postgres:
    Host: "${ZITADEL_DATABASE_HOST:-smarkee-database}"
    Port: "${ZITADEL_DATABASE_PORT:-5432}"
    Database: "${ZITADEL_DATABASE_NAME:-smarkee}"
    User:
      Username: "${ZITADEL_DATABASE_USER:-smarkee}"
      Password: "${ZITADEL_DATABASE_PASSWORD:-smarkee_password}"
    Admin:
      Username: "${ZITADEL_DATABASE_USER:-smarkee}"
      Password: "${ZITADEL_DATABASE_PASSWORD:-smarkee_password}"
      SSL:
        Mode: disable
