# Configuração do Kong (DB-less mode)
database = off
declarative_config = /kong/declarative/kong.yml

# Logs
proxy_access_log = /dev/stdout
admin_access_log = /dev/stdout
proxy_error_log = /dev/stderr
admin_error_log = /dev/stderr

# Interfaces de escuta
admin_listen = 0.0.0.0:8001, 0.0.0.0:8444 ssl
proxy_listen = 0.0.0.0:8000, 0.0.0.0:8443 ssl
